apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-testing-pipeline
  namespace: testing-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-testing-pipeline
  template:
    metadata:
      labels:
        app: k8s-testing-pipeline
    spec:
      containers:
        - name: api
          image: lehender/k8s-testing-pipeline:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Namespace
metadata:
  name: testing-pipeline
