name: CI - Test and Lint

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/k8s-testing-pipeline:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Debug environment
        run: |
          python -V
          pwd
          ls -R
          python - <<'PY'
          import sys, os
          print("CWD:", os.getcwd())
          print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
          print("sys.path:", sys.path)
          import importlib; importlib.import_module("app.main")
          print("Imported app.main OK")
          PY
        env:
          PYTHONPATH: .

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q tests/

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: ${{ env.IMAGE }}

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/lehender/k8s-testing-pipeline:latest
